workspace:
  base: /front
  path: src/github.com/derFischer/swms-frontend
pipeline:
  build:
    image: maven:3.6.0-jdk-8-alpine
    commands:
      - npm install
  publish:
    image: plugins/docker
    repo: derFischer/swms-frontend
    tags: ["latest", "v2"]
    secrets: [ docker_username, docker_password ]
    dockerfile: Dockerfile
